
# This file is automatically generated, you probably don't want to edit this

factorial3levelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "factorial3levelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factorA = NULL,
            factorB = NULL,
            factorC = NULL,
            dep = NULL,
            varEq = TRUE,
            showPlot = TRUE,
            showANOVA = TRUE, ...) {

            super$initialize(
                package="FactorialDesign",
                name="factorial3level",
                requiresData=TRUE,
                ...)

            private$..factorA <- jmvcore::OptionVariable$new(
                "factorA",
                factorA,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..factorB <- jmvcore::OptionVariable$new(
                "factorB",
                factorB,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..factorC <- jmvcore::OptionVariable$new(
                "factorC",
                factorC,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=TRUE)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)
            private$..showANOVA <- jmvcore::OptionBool$new(
                "showANOVA",
                showANOVA,
                default=TRUE)

            self$.addOption(private$..factorA)
            self$.addOption(private$..factorB)
            self$.addOption(private$..factorC)
            self$.addOption(private$..dep)
            self$.addOption(private$..varEq)
            self$.addOption(private$..showPlot)
            self$.addOption(private$..showANOVA)
        }),
    active = list(
        factorA = function() private$..factorA$value,
        factorB = function() private$..factorB$value,
        factorC = function() private$..factorC$value,
        dep = function() private$..dep$value,
        varEq = function() private$..varEq$value,
        showPlot = function() private$..showPlot$value,
        showANOVA = function() private$..showANOVA$value),
    private = list(
        ..factorA = NA,
        ..factorB = NA,
        ..factorC = NA,
        ..dep = NA,
        ..varEq = NA,
        ..showPlot = NA,
        ..showANOVA = NA)
)

factorial3levelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "factorial3levelResults",
    inherit = jmvcore::Group,
    active = list(
        anovaTable = function() private$.items[["anovaTable"]],
        effects = function() private$.items[["effects"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Factorial Design - 3 Levels")
            self$add(jmvcore::Table$new(
                options=options,
                name="anovaTable",
                title="ANOVA Table",
                rows=0,
                visible="(showANOVA)",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Source", 
                        `type`="text"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="ss", 
                        `title`="Sum of Squares", 
                        `type`="number"),
                    list(
                        `name`="ms", 
                        `title`="Mean Square", 
                        `type`="number"),
                    list(
                        `name`="F", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Main Effects Summary",
                rows=0,
                visible="(showANOVA)",
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="levels", 
                        `title`="Levels", 
                        `type`="text"),
                    list(
                        `name`="means", 
                        `title`="Means", 
                        `type`="text"),
                    list(
                        `name`="effect", 
                        `title`="Effect Size", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Interaction Plot",
                width=500,
                height=400,
                renderFun=".plot",
                visible="(showPlot)"))}))

factorial3levelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "factorial3levelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FactorialDesign",
                name = "factorial3level",
                version = c(1,0,5),
                options = options,
                results = factorial3levelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Factorial Design - 3 Levels
#'
#' 
#' @param data .
#' @param factorA .
#' @param factorB .
#' @param factorC .
#' @param dep .
#' @param varEq .
#' @param showPlot .
#' @param showANOVA .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$anovaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$anovaTable$asDF}
#'
#' \code{as.data.frame(results$anovaTable)}
#'
#' @export
factorial3level <- function(
    data,
    factorA,
    factorB,
    factorC,
    dep,
    varEq = TRUE,
    showPlot = TRUE,
    showANOVA = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("factorial3level requires jmvcore to be installed (restart may be required)")

    if ( ! missing(factorA)) factorA <- jmvcore::resolveQuo(jmvcore::enquo(factorA))
    if ( ! missing(factorB)) factorB <- jmvcore::resolveQuo(jmvcore::enquo(factorB))
    if ( ! missing(factorC)) factorC <- jmvcore::resolveQuo(jmvcore::enquo(factorC))
    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(factorA), factorA, NULL),
            `if`( ! missing(factorB), factorB, NULL),
            `if`( ! missing(factorC), factorC, NULL),
            `if`( ! missing(dep), dep, NULL))


    options <- factorial3levelOptions$new(
        factorA = factorA,
        factorB = factorB,
        factorC = factorC,
        dep = dep,
        varEq = varEq,
        showPlot = showPlot,
        showANOVA = showANOVA)

    analysis <- factorial3levelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

