
# This file is automatically generated, you probably don't want to edit this

factorial2levelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "factorial2levelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            factors = NULL,
            response = NULL,
            mainEffects = TRUE,
            interactionPlot = TRUE,
            regressionTable = TRUE, ...) {

            super$initialize(
                package="FactorialDesign",
                name="factorial2level",
                requiresData=TRUE,
                ...)

            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..mainEffects <- jmvcore::OptionBool$new(
                "mainEffects",
                mainEffects,
                default=TRUE)
            private$..interactionPlot <- jmvcore::OptionBool$new(
                "interactionPlot",
                interactionPlot,
                default=TRUE)
            private$..regressionTable <- jmvcore::OptionBool$new(
                "regressionTable",
                regressionTable,
                default=TRUE)

            self$.addOption(private$..factors)
            self$.addOption(private$..response)
            self$.addOption(private$..mainEffects)
            self$.addOption(private$..interactionPlot)
            self$.addOption(private$..regressionTable)
        }),
    active = list(
        factors = function() private$..factors$value,
        response = function() private$..response$value,
        mainEffects = function() private$..mainEffects$value,
        interactionPlot = function() private$..interactionPlot$value,
        regressionTable = function() private$..regressionTable$value),
    private = list(
        ..factors = NA,
        ..response = NA,
        ..mainEffects = NA,
        ..interactionPlot = NA,
        ..regressionTable = NA)
)

factorial2levelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "factorial2levelResults",
    inherit = jmvcore::Group,
    active = list(
        coefficients = function() private$.items[["coefficients"]],
        metrics = function() private$.items[["metrics"]],
        equation = function() private$.items[["equation"]],
        effects = function() private$.items[["effects"]],
        mainEffectsPlot = function() private$.items[["mainEffectsPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Factorial Design - 2 Levels")
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Regression Coefficients",
                rows=0,
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Std. Error", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t-value", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="metrics",
                title="Model Fit Statistics",
                rows=0,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="equation",
                title="Regression Equation",
                rows=0,
                columns=list(
                    list(
                        `name`="equation", 
                        `title`="Equation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Main Effects",
                rows=0,
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="effect", 
                        `title`="Effect Size", 
                        `type`="number"),
                    list(
                        `name`="low_level", 
                        `title`="Low Level", 
                        `type`="number"),
                    list(
                        `name`="high_level", 
                        `title`="High Level", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainEffectsPlot",
                title="Main Effects Plot",
                width=600,
                height=400,
                renderFun=".plot"))}))

factorial2levelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "factorial2levelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FactorialDesign",
                name = "factorial2level",
                version = c(1,0,5),
                options = options,
                results = factorial2levelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Factorial Design - 2 Levels
#'
#' 
#' @param data Input dataset
#' @param factors Independent variables (factors) for the factorial design
#' @param response Dependent variable (response) to be analyzed
#' @param mainEffects Display main effects plot
#' @param interactionPlot Display interaction effects plot
#' @param regressionTable Display regression coefficients table
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$metrics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$equation} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$mainEffectsPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coefficients$asDF}
#'
#' \code{as.data.frame(results$coefficients)}
#'
#' @export
factorial2level <- function(
    data,
    factors,
    response,
    mainEffects = TRUE,
    interactionPlot = TRUE,
    regressionTable = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("factorial2level requires jmvcore to be installed (restart may be required)")

    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(response), response, NULL))


    options <- factorial2levelOptions$new(
        factors = factors,
        response = response,
        mainEffects = mainEffects,
        interactionPlot = interactionPlot,
        regressionTable = regressionTable)

    analysis <- factorial2levelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

